name: syncfusion_flutter_pdfviewer_web
description: Web platform implementation of the Flutter PDF Viewer library that lets you view the PDF documents seamlessly and efficiently.
version: 19.1.54-beta
homepage: https://gitlab.syncfusion.com/essential-studio/flutter-pdfviewer

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  syncfusion_flutter_pdfviewer_platform_interface:
    path: ../syncfusion_flutter_pdfviewer_platform_interface

flutter:
  plugin:
    platforms:
     web:
        pluginClass: SyncfusionFlutterPdfViewerPlugin
        fileName: pdfviewer_web.dart
