name: syncfusion_flutter_maps
description: A Flutter Maps library for creating beautiful, interactive, and customizable maps from shape files or WMTS services to visualize the geographical area.
version: 19.1.54-beta
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_maps

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_core:
    git: 
      url: git@github.com:shazadmaved/sync_widget.git
      path: packages/syncfusion_flutter_core/
      ref: main
  arrow_path: ^2.0.0
  collection: ">=1.9.0 <=1.15.0"
  http: ">=0.12.0 <=0.13.0"

flutter:

  
